/* ===========================================================================
   flags.js — a flag for a team's country, whatever country that is.

   GENERATED by core/gen_flags.py from core/countries.py. Do not hand-edit; add
   the country there and re-run, so the feedback tool's ban list learns it too.

   The emoji is not stored, it is computed: a flag emoji is just the country's
   two-letter code with each letter shifted into the Unicode regional-indicator
   block. So there is no list to keep up to date, and no country can end up with
   a blank beside it.

   Region strings come from your Tabbycat institution records, and tab writers
   spell them however they like, so ALIASES covers the common alternates ("UK",
   "USA", "Korea", "Viet Nam"). A region with no match simply gets no mark, and
   a platform with no flag glyphs (Windows) shows the two-letter code instead.

   A flag-coloured background wash on the blocks was built and thrown away. At
   any opacity that keeps a team name legible, similar flags land on the same
   pale tint and dark-on-light detail vanishes, so the wash carried no
   information and cost contrast. The emoji says the same thing in 14 pixels.
   ========================================================================= */

const COUNTRY_CODES = {
  "Afghanistan": "AF",
  "Albania": "AL",
  "Algeria": "DZ",
  "Andorra": "AD",
  "Angola": "AO",
  "Argentina": "AR",
  "Armenia": "AM",
  "Australia": "AU",
  "Austria": "AT",
  "Azerbaijan": "AZ",
  "Bahamas": "BS",
  "Bahrain": "BH",
  "Bangladesh": "BD",
  "Barbados": "BB",
  "Belarus": "BY",
  "Belgium": "BE",
  "Belize": "BZ",
  "Benin": "BJ",
  "Bhutan": "BT",
  "Bolivia": "BO",
  "Bosnia and Herzegovina": "BA",
  "Botswana": "BW",
  "Brazil": "BR",
  "Brunei": "BN",
  "Bulgaria": "BG",
  "Burkina Faso": "BF",
  "Burundi": "BI",
  "Cambodia": "KH",
  "Cameroon": "CM",
  "Canada": "CA",
  "Cape Verde": "CV",
  "Central African Republic": "CF",
  "Chad": "TD",
  "Chile": "CL",
  "China": "CN",
  "Colombia": "CO",
  "Comoros": "KM",
  "Costa Rica": "CR",
  "Croatia": "HR",
  "Cuba": "CU",
  "Cyprus": "CY",
  "Czechia": "CZ",
  "Democratic Republic of the Congo": "CD",
  "Denmark": "DK",
  "Djibouti": "DJ",
  "Dominica": "DM",
  "Dominican Republic": "DO",
  "Ecuador": "EC",
  "Egypt": "EG",
  "El Salvador": "SV",
  "Equatorial Guinea": "GQ",
  "Eritrea": "ER",
  "Estonia": "EE",
  "Eswatini": "SZ",
  "Ethiopia": "ET",
  "Fiji": "FJ",
  "Finland": "FI",
  "France": "FR",
  "Gabon": "GA",
  "Gambia": "GM",
  "Georgia": "GE",
  "Germany": "DE",
  "Ghana": "GH",
  "Greece": "GR",
  "Grenada": "GD",
  "Guatemala": "GT",
  "Guinea": "GN",
  "Guyana": "GY",
  "Haiti": "HT",
  "Honduras": "HN",
  "Hong Kong": "HK",
  "Hungary": "HU",
  "Iceland": "IS",
  "India": "IN",
  "Indonesia": "ID",
  "Iran": "IR",
  "Iraq": "IQ",
  "Ireland": "IE",
  "Israel": "IL",
  "Italy": "IT",
  "Ivory Coast": "CI",
  "Jamaica": "JM",
  "Japan": "JP",
  "Jordan": "JO",
  "Kazakhstan": "KZ",
  "Kenya": "KE",
  "Kiribati": "KI",
  "Kosovo": "XK",
  "Kuwait": "KW",
  "Kyrgyzstan": "KG",
  "Laos": "LA",
  "Latvia": "LV",
  "Lebanon": "LB",
  "Lesotho": "LS",
  "Liberia": "LR",
  "Libya": "LY",
  "Liechtenstein": "LI",
  "Lithuania": "LT",
  "Luxembourg": "LU",
  "Macau": "MO",
  "Madagascar": "MG",
  "Malawi": "MW",
  "Malaysia": "MY",
  "Maldives": "MV",
  "Mali": "ML",
  "Malta": "MT",
  "Marshall Islands": "MH",
  "Mauritania": "MR",
  "Mauritius": "MU",
  "Mexico": "MX",
  "Micronesia": "FM",
  "Moldova": "MD",
  "Monaco": "MC",
  "Mongolia": "MN",
  "Montenegro": "ME",
  "Morocco": "MA",
  "Mozambique": "MZ",
  "Myanmar": "MM",
  "Namibia": "NA",
  "Nauru": "NR",
  "Nepal": "NP",
  "Netherlands": "NL",
  "New Zealand": "NZ",
  "Nicaragua": "NI",
  "Niger": "NE",
  "Nigeria": "NG",
  "North Macedonia": "MK",
  "Norway": "NO",
  "Oman": "OM",
  "Pakistan": "PK",
  "Palau": "PW",
  "Palestine": "PS",
  "Panama": "PA",
  "Papua New Guinea": "PG",
  "Paraguay": "PY",
  "Peru": "PE",
  "Philippines": "PH",
  "Poland": "PL",
  "Portugal": "PT",
  "Qatar": "QA",
  "Romania": "RO",
  "Russia": "RU",
  "Rwanda": "RW",
  "Samoa": "WS",
  "Saudi Arabia": "SA",
  "Senegal": "SN",
  "Serbia": "RS",
  "Seychelles": "SC",
  "Sierra Leone": "SL",
  "Singapore": "SG",
  "Slovakia": "SK",
  "Slovenia": "SI",
  "Solomon Islands": "SB",
  "Somalia": "SO",
  "South Africa": "ZA",
  "South Korea": "KR",
  "South Sudan": "SS",
  "Spain": "ES",
  "Sri Lanka": "LK",
  "Sudan": "SD",
  "Suriname": "SR",
  "Sweden": "SE",
  "Switzerland": "CH",
  "Syria": "SY",
  "Taiwan": "TW",
  "Tajikistan": "TJ",
  "Tanzania": "TZ",
  "Thailand": "TH",
  "Timor-Leste": "TL",
  "Togo": "TG",
  "Tonga": "TO",
  "Trinidad and Tobago": "TT",
  "Tunisia": "TN",
  "Turkey": "TR",
  "Turkmenistan": "TM",
  "Tuvalu": "TV",
  "Uganda": "UG",
  "Ukraine": "UA",
  "United Arab Emirates": "AE",
  "United Kingdom": "GB",
  "United States": "US",
  "Uruguay": "UY",
  "Uzbekistan": "UZ",
  "Vanuatu": "VU",
  "Venezuela": "VE",
  "Vietnam": "VN",
  "Yemen": "YE",
  "Zambia": "ZM",
  "Zimbabwe": "ZW"
};

const ALIASES = {
  "America": "United States",
  "Britain": "United Kingdom",
  "Burma": "Myanmar",
  "Cabo Verde": "Cape Verde",
  "Congo": "Democratic Republic of the Congo",
  "Cote d'Ivoire": "Ivory Coast",
  "Czech Republic": "Czechia",
  "DRC": "Democratic Republic of the Congo",
  "East Timor": "Timor-Leste",
  "Emirates": "United Arab Emirates",
  "England": "United Kingdom",
  "Great Britain": "United Kingdom",
  "Holland": "Netherlands",
  "Hongkong": "Hong Kong",
  "Korea": "South Korea",
  "Macao": "Macau",
  "Northern Ireland": "United Kingdom",
  "PRC": "China",
  "ROK": "South Korea",
  "Republic of Korea": "South Korea",
  "Scotland": "United Kingdom",
  "Swaziland": "Eswatini",
  "Turkiye": "Turkey",
  "U.S.": "United States",
  "UAE": "United Arab Emirates",
  "UK": "United Kingdom",
  "US": "United States",
  "USA": "United States",
  "United States of America": "United States",
  "Viet Nam": "Vietnam",
  "Wales": "United Kingdom"
};

/** Two-letter code for however the tab spelled a region. null if unknown. */
function regionCode(region) {
  if (!region) return null;
  const r = String(region).trim();
  const direct = COUNTRY_CODES[r] || COUNTRY_CODES[ALIASES[r] || ""];
  if (direct) return direct;
  const lower = r.toLowerCase();
  for (const k in COUNTRY_CODES) if (k.toLowerCase() === lower) return COUNTRY_CODES[k];
  for (const k in ALIASES) if (k.toLowerCase() === lower) return COUNTRY_CODES[ALIASES[k]] || null;
  return null;
}

/** The flag emoji, built from the code. null if the region is not a country. */
function flagEmoji(region) {
  const a2 = regionCode(region);
  if (!a2) return null;
  return String.fromCodePoint(...[...a2.toUpperCase()].map(c => 0x1F1E6 + c.charCodeAt(0) - 65));
}

/** The mark, carrying the country name for anyone reading by ear. Falls back to
    the two-letter code where the platform has no flag glyphs. */
function flagMark(region) {
  const a2 = regionCode(region);
  if (!a2) return null;
  const e = flagEmoji(region);
  return el("span", { class: "fl", role: "img", "aria-label": region,
                      title: region, text: e || a2 });
}
