#!/usr/bin/env python3
"""
gen_flags.py — write fold/src/flags.js from core/countries.py.

The Fold is a single static page with no build dependencies, so the flag data is
generated into the repo rather than fetched. Re-run this if countries.py changes:

    python3 core/gen_flags.py
"""
import json, os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import countries

OUT = os.path.join(os.path.dirname(HERE), "fold", "src", "flags.js")

HEAD = '''/* ===========================================================================
   flags.js — a flag for a team's country, whatever country that is.

   GENERATED by core/gen_flags.py from core/countries.py. Do not hand-edit; add
   the country there and re-run, so the feedback tool's ban list learns it too.

   The emoji is not stored, it is computed: a flag emoji is just the country's
   two-letter code with each letter shifted into the Unicode regional-indicator
   block. So there is no list to keep up to date, and no country can end up with
   a blank beside it.

   Region strings come from your Tabbycat institution records, and tab writers
   spell them however they like, so ALIASES covers the common alternates ("UK",
   "USA", "Korea", "Viet Nam"). A region with no match simply gets no mark, and
   a platform with no flag glyphs (Windows) shows the two-letter code instead.

   A flag-coloured background wash on the blocks was built and thrown away. At
   any opacity that keeps a team name legible, similar flags land on the same
   pale tint and dark-on-light detail vanishes, so the wash carried no
   information and cost contrast. The emoji says the same thing in 14 pixels.
   ========================================================================= */

'''

TAIL = '''
/** Two-letter code for however the tab spelled a region. null if unknown. */
function regionCode(region) {
  if (!region) return null;
  const r = String(region).trim();
  const direct = COUNTRY_CODES[r] || COUNTRY_CODES[ALIASES[r] || ""];
  if (direct) return direct;
  const lower = r.toLowerCase();
  for (const k in COUNTRY_CODES) if (k.toLowerCase() === lower) return COUNTRY_CODES[k];
  for (const k in ALIASES) if (k.toLowerCase() === lower) return COUNTRY_CODES[ALIASES[k]] || null;
  return null;
}

/** The flag emoji, built from the code. null if the region is not a country. */
function flagEmoji(region) {
  const a2 = regionCode(region);
  if (!a2) return null;
  return String.fromCodePoint(...[...a2.toUpperCase()].map(c => 0x1F1E6 + c.charCodeAt(0) - 65));
}

/** The mark, carrying the country name for anyone reading by ear. Falls back to
    the two-letter code where the platform has no flag glyphs. */
function flagMark(region) {
  const a2 = regionCode(region);
  if (!a2) return null;
  const e = flagEmoji(region);
  return el("span", { class: "fl", role: "img", "aria-label": region,
                      title: region, text: e || a2 });
}
'''


def main():
    codes = json.dumps(countries.COUNTRIES, ensure_ascii=False, indent=2, sort_keys=True)
    aliases = json.dumps(countries.ALIASES, ensure_ascii=False, indent=2, sort_keys=True)
    js = (HEAD
          + f"const COUNTRY_CODES = {codes};\n\n"
          + f"const ALIASES = {aliases};\n"
          + TAIL)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(js)
    print(f"wrote {os.path.relpath(OUT, os.path.dirname(HERE))} — "
          f"{len(countries.COUNTRIES)} countries, {len(countries.ALIASES)} aliases")


if __name__ == "__main__":
    main()
